name: Deploy

on:
  push:
    branches:
      - main # or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
          node-version: '20'

    - name: SSH and deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > keyfile
        chmod 600 keyfile
        ssh -t -i  "keyfile" ubuntu@ec2-13-236-90-145.ap-southeast-2.compute.amazonaws.com "sudo bash ~/deploy.sh"

